In [4]:
import numpy as np
a=np.array([1.0,2.0,6.0])
print(a)
print(type(a))

[1. 2. 6.]
<class 'numpy.ndarray'>


In [6]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [7]:
print(2*x)

[2. 4. 6.]


In [12]:
a=np.array([[1.0,2.0],[2.0,4.0]])
print(a)
print(a.shape)
print(a.dtype)

[[1. 2.]
 [2. 4.]]
(2, 2)
float64


In [13]:
x=np.array([[1,2],[2,4]])
y=np.array([[3,6],[4,8]])
print(x+y)
print(2*x)

[[ 4  8]
 [ 6 12]]
[[2 4]
 [4 8]]


In [18]:
#broadcast
#比較 2 array的shape,只有 1.当前维度的值相等 2.当前维度的值有一个是1 可以
#2*[[1,2],[2,4]] = [[2,2],[2,2]]*[[1,2],[2,4]] 
x=np.array([[1,2],[2,4]])
y=np.array([2,4])
print(x+y)

[[3 6]
 [4 8]]


In [19]:
x=np.array([2,4,6,8])
y=np.array([2])
print(x+y)

[ 4  6  8 10]


In [23]:
x=np.array([[1,2],[2,4],[3,6]])
print(x)
print(x[0])
print(x[0][1])

[[1 2]
 [2 4]
 [3 6]]
[1 2]
2


In [22]:
for row in x:
    print(row)

[1 2]
[2 4]
[3 6]


In [24]:
X=x.flatten()
print(X)


[1 2 2 4 3 6]


In [31]:
#可用array存取元素
print(X[[0,2,4]])
print(X[np.array([0,2,4])])

[1 2 3]
[1 2 3]


In [32]:
print(X>2)

[False False False  True  True  True]


In [33]:
print(X[X>2])

[4 3 6]
